const DISPOSABLE_EMAIL_DOMAINS = new Set([
  "10minutemail.com",
  "10minmail.com",
  "cool.fr.nf",
  "courriel.fr.nf",
  "discard.email",
  "dispostable.com",
  "emailondeck.com",
  "fakeinbox.com",
  "getairmail.com",
  "getnada.com",
  "grr.la",
  "guerrillamail.com",
  "guerrillamailblock.com",
  "inboxkitten.com",
  "jetable.fr.nf",
  "jetable.org",
  "kasmail.com",
  "mailcatch.com",
  "maildrop.cc",
  "mailinator.com",
  "mailnesia.com",
  "mailnull.com",
  "mega.zik.dj",
  "meltmail.com",
  "mintemail.com",
  "moakt.com",
  "mytemp.email",
  "nowmymail.com",
  "objectmail.com",
  "pokemail.net",
  "proxymail.pro",
  "ruu.kr",
  "sharklasers.com",
  "spam4.me",
  "spambog.com",
  "spamgourmet.com",
  "speed.1s.fr",
  "temp-mail.org",
  "tempail.com",
  "tempinbox.com",
  "tempmail.com",
  "tempr.email",
  "throwaway.email",
  "tmpmail.org",
  "trash-mail.com",
  "trashmail.com",
  "trashmail.fr",
  "wegwerfmail.de",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase().trim();
  if (!domain) {
    return false;
  }
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}
